//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antinori.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntinoriEntities : DbContext
    {
        public AntinoriEntities()
            : base("name=AntinoriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<SubSections> SubSections { get; set; }
        public virtual DbSet<Transcriptions> Transcriptions { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
    }
}
