//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antinori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pages()
        {
            this.Transcriptions = new HashSet<Transcriptions>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int NumericOrder { get; set; }
        public string CompleteOrder { get; set; }
        public string PhotoPath { get; set; }
        public string BigPhotoPath { get; set; }
        public string BookTitle { get; set; }
        public string SectionName { get; set; }
        public string SubSection { get; set; }
    
        public virtual SubSections SubSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transcriptions> Transcriptions { get; set; }
    }
}
