//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antinori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcriptions
    {
        public string Id { get; set; }
        public string TEI { get; set; }
        public string Page { get; set; }
        public bool IsApproved { get; set; }
        public string ProposedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ProposedDate { get; set; }
    
        public virtual Pages Pages { get; set; }
    }
}
