//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Id { get; set; }
        public string Rif_Tabella { get; set; }
        public string Rif_Id { get; set; }
        public string Operazione_Tipo { get; set; }
        public string Operazione_Esito { get; set; }
        public bool Operazione_Riuscita { get; set; }
        public string Operazione_Dettagli1 { get; set; }
        public string Operazione_Dettagli2 { get; set; }
        public string Operazione_Dettagli3 { get; set; }
        public string Operazione_Dettagli4 { get; set; }
        public System.DateTime Operazione_Data { get; set; }
        public string Operazione_Username { get; set; }
    }
}
